name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'

jobs:

  ci:
    name: Run CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: Run tests
        run: make ci
